service:
  # ИД владельца бота. Для передачи своего бота другому владельцу надо сначала пообщаться с @BotFather
  botOwner: 111111111
  botName: your_bot_name
  #Токен бота
  botToken: your_bot_token
  dbPath: ./pick_a_pic_bot.db
#Настройки логики
logic:
  #Коэффициент изменения рейтинга ЭЛО: X/sqrt(completed), где X - этот параметр, completed - число полностью завершенных голосований
  coefficient: 100
  maxEachShows: 2